// SPI top module implementation 
// Here only 8 data bits are transferred
// sclk signal is generated by master and is different from system clk

`timescale 1ns/1ps
module spi_top (dout_s,dout_m,done_s,done_m,cpol,cpha,din_s,din_m,dvsr,start,clk,rst);
  
  output logic done_s,done_m;
  output logic [7:0] dout_s,dout_m;
  input logic cpol,cpha,start,clk,rst;
  input logic [7:0] din_m,din_s;
  input logic [15:0] dvsr;

  logic mosi_i,miso_i,sclk_i,ready_i;

  parameter DBITS = 8; //total number of data bits to be communicated
  
  spi_m master (.mosi(mosi_i),.rst(rst),.clk(clk),.dvsr(dvsr),.miso(miso_i),.done(done_m),.ready(ready_i),.sclk(sclk_i),.dout(dout_m),.cpol(cpol),.cpha(cpha),.start(start),.din(din_m));
  spi_s slave (.miso(miso_i),.mosi(mosi_i),.done(done_s),.din(din_s),.rst(rst),.sclk(sclk_i),.dout(dout_s),.cpol(cpol),.cpha(cpha),.dout(dout_s));
 
  
endmodule
 
